// Sunsprite API declarations, version 1.0.
// Generated by `pnpm run snapshot-api` — a permanent, historical snapshot. Do not edit.

import type { Point, PointArg } from "../../Point"
import type { Returnable, MouseInputAction, PointerAction, ScrollAction } from "../../types"
import type { Cursor } from "../../mixins/Interactable"

export type PositionableProps = {
    /** Horizontal position in the world. */
    x?: number

    /** Vertical position in the world. */
    y?: number

    /** Position in the world. */
    position?: Vector2Like

    /** Position in the world (alias of position). */
    pos?: Vector2Like

    /** Horizontal position on the screen. */
    screenX?: number

    /** Vertical position on the screen. */
    screenY?: number

    /** Position on the screen. */
    screenPosition?: Vector2Like

    /** Position on the screen (alias of position). */
    screenPos?: Vector2Like
}

export type SizableProps = {
    /** Horizontal size in pixels. */
    width?: number

    /** Vertical size in pixels. */
    height?: number

    /** Factor to multiply size by. Setting scale to 2 will double its size; 0.5 will halve it. */
    scale?: number
}

export type RotatableProps = {
    /** Rotation angle in degrees. */
    rotation?: number

    /** Rotation angle in radians. */
    radians?: number
}

export type ViewableProps = {
    /** Transparency, decimal value that ranges from 0.0 (transparent) to 1.0 (opaque). */
    alpha?: number

    /** The render order. Objects with higher layer values will show in front of objects with lower values. */
    layer?: number

    /** Whether this object is currently visible. */
    visible?: boolean
}

export type InteractableProps = {
    /** Whether this object can be dragged with the mouse. */
    draggable?: boolean

    /** The cursor shown when the mouse is over this object. */
    cursor?: Cursor

    /** Register mouse event functions, used to more easily assign several actions at once. */
    onMouse?: MouseInputAction

    /** Register a function to run when clicking this object. */
    onClick?: PointerAction

    /** Register a function to run when releasing a click on this object. */
    onRelease?: PointerAction

    /** Register a function to run when quickly left clicking twice on this object. */
    onDoubleClick?: PointerAction

    /** Register a function to run when left clicking this object. */
    onLeftClick?: PointerAction

    /** Register a function to run when releasing a left click on this object. */
    onLeftRelease?: PointerAction

    /** Register a function to run when right clicking this object. */
    onRightClick?: PointerAction

    /** Register a function to run when releasing a right click on this object. */
    onRightRelease?: PointerAction

    /** Register a function to run when middle clicking this object. */
    onMiddleClick?: PointerAction

    /** Register a function to run when releasing a middle click on this object. */
    onMiddleRelease?: PointerAction

    /** Register a function to run when the mouse first starts overlapping this object. */
    onMouseEnter?: PointerAction

    /** Register a function to run when the mouse first stops overlapping this object. */
    onMouseExit?: PointerAction

    /** Register a function to run when the mouse moves while overlapping over this object. */
    onMouseMove?: PointerAction

    /** Register a function to run repeatedly while this object is being dragged. */
    onDrag?: PointerAction

    /** Register a function to run when this object first starts being dragged. */
    onDragStart?: PointerAction

    /** Register a function to run when this object first stops being dragged. */
    onDragEnd?: PointerAction

    /** Register a function to run when scrolling while hovering over this object. */
    onScroll?: PointerAction
}

export type GameObjectProps = PositionableProps & SizableProps & RotatableProps & InteractableProps & ViewableProps

export type SpriteProps = GameObjectProps & {
    /** A URL path to the sprite's image. */
    src?: string
}

export declare class Sprite {
    constructor(options?: SpriteProps)

    /** A URL path to the sprite's image. */
    get src(): string
    set src(keyOrPath: string | undefined | null)
}

export type RectangleProps = GameObjectProps & {
    /** The fill color. */
    color?: string
}

export declare class Rectangle {
    constructor(options?: RectangleProps)

    /** The fill color. */
    color: string
}

export type CircleProps = GameObjectProps & {
    /** The fill color. */
    color?: string

    /** The distance from the center of the circle to the edge. */
    radius?: number
}

export declare class Circle {
    constructor(options?: CircleProps)

    /** The fill color. */
    color: string

    /** Transparency, decimal value that ranges from 0.0 (transparent) to 1.0 (opaque). */
    alpha: number

    /** The distance from the center of the circle to the edge. */
    radius: number
}

export type LabelProps = GameObjectProps & {
    /** Text content of the label. */
    text?: string | string[]

    /** Font size. */
    size?: number

    /** Font family. */
    font?: string

    /** Fill color. */
    color?: string
}

export declare class Label {
    constructor(options?: LabelProps)

    /** Text content of the label. */
    get text(): string
    set text(text: string | string[])

    /** Font size. */
    size: number

    /** Font family. */
    font: string

    /** Fill color. */
    color: string
}

export type LineProps = RotatableProps & ViewableProps & {
    /** Position of end point A. */
    pointA?: Returnable<Vector2Like>

    /** Position of end point B. */
    pointB?: Returnable<Vector2Like>

    /** The color of the line. */
    color?: string

    /** The thickness of the line. (Default = 2) */
    thickness?: number
}

export declare class Line {
    constructor(options?: LineProps)

    /** How long this object has existed, in seconds (not including paused time). */
    readonly age: number

    /** How long this object has existed, in milliseconds (not including paused time). */
    readonly ageMs: number

    /** Transparency, decimal value that ranges from 0.0 (transparent) to 1.0 (opaque). */
    alpha: number

    /** The render order. Objects with higher layer values will show in front of objects with lower values. */
    layer: number

    /** Whether this object is currently visible. */
    visible: boolean

    /** Show this object. */
    show(): void

    /** Hide this object. */
    hide(): void

    /** Rotation angle in degrees. */
    rotation: number

    /** Rotation angle in radians. */
    radians: number

    /** Position of end point A. */
    get pointA(): Vector2
    set pointA(pointA: Returnable<PointArg | number[]>)

    /** Position of end point B. */
    get pointB(): Vector2
    set pointB(pointB: Returnable<PointArg | number[]>)

    /** The color of the line. */
    color: string

    /** The thickness of the line. */
    thickness: number

    /** The distance between point A and point B. */
    readonly length: number

    /** Set both endpoints of the line at once. */
    setPoints(pointA: Vector2Like, pointB: Vector2Like): void
}

export type HLineProps = ViewableProps & {
    /** The vertical position of the line. */
    y?: number

    /** The color of the line. */
    color?: string

    /** The thickness of the line. */
    thickness?: number
}

export declare class HLine {
    constructor(options?: HLineProps)

    /** How long this object has existed, in seconds (not including paused time). */
    readonly age: number

    /** How long this object has existed, in milliseconds (not including paused time). */
    readonly ageMs: number

    /** Transparency, decimal value that ranges from 0.0 (transparent) to 1.0 (opaque). */
    alpha: number

    /** The render order. Objects with higher layer values will show in front of objects with lower values. */
    layer: number

    /** Whether this object is currently visible. */
    visible: boolean

    /** Show this object. */
    show(): void

    /** Hide this object. */
    hide(): void

    /** The vertical position of the line. */
    y: number

    /** The color of the line. */
    color: string

    /** The thickness of the line. */
    thickness: number
}

export type VLineProps = ViewableProps & {
    /** The horizontal position of the line. */
    x?: number

    /** The color of the line. */
    color?: string

    /** The thickness of the line. */
    thickness?: number
}

export declare class VLine {
    constructor(options?: VLineProps)

    /** How long this object has existed, in seconds (not including paused time). */
    readonly age: number

    /** How long this object has existed, in milliseconds (not including paused time). */
    readonly ageMs: number

    /** Transparency, decimal value that ranges from 0.0 (transparent) to 1.0 (opaque). */
    alpha: number

    /** The render order. Objects with higher layer values will show in front of objects with lower values. */
    layer: number

    /** Whether this object is currently visible. */
    visible: boolean

    /** Show this object. */
    show(): void

    /** Hide this object. */
    hide(): void

    /** The horizontal position of the line. */
    x: number

    /** The color of the line. */
    color: string

    /** The thickness of the line. */
    thickness: number
}
