import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { generateApiDeclarations } from './api-codegen/index'
import { renderGeneratedModule } from './api-codegen/render'
import { apiPath } from './api-codegen/sources'
import { checkApiCompleteness } from './api-codegen/completeness'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

async function main() {
    const generated = generateApiDeclarations()
    const content = renderGeneratedModule(generated, [
        '// AUTO-GENERATED by `pnpm run generate-api` — do not edit directly.',
        '// Regenerate after changing any mixin or concrete class in src/assets/api/.',
    ])

    const outDir = apiPath('generated')
    mkdirSync(outDir, { recursive: true })
    const outFile = path.join(outDir, 'apiDeclarations.generated.ts')
    writeFileSync(outFile, content, 'utf8')
    console.log(`Wrote ${path.relative(path.resolve(__dirname, '..'), outFile)}`)

    // Must run after the writeFileSync above (as a dynamic import, not a
    // static one) — apiLib.ts imports from the file just written, so a
    // hoisted static import would silently check the previous run's output.
    await checkApiCompleteness()
    console.log('apiLib.ts covers every key in core.ts\'s real api object.')
}

main().catch((err) => {
    console.error(err instanceof Error ? err.message : err)
    process.exit(1)
})
