import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { generateApiDeclarations } from './api-codegen/index'
import { apiPath } from './api-codegen/sources'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function esc(text: string): string {
    // Escape backtick-string hazards so generated content stays a valid template literal.
    return text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function main() {
    const generated = generateApiDeclarations()
    const lines: string[] = [
        '// AUTO-GENERATED by `pnpm run generate-api` — do not edit directly.',
        '// Regenerate after changing any mixin or concrete class in src/assets/api/.',
        '',
    ]

    const mixinExportName: Record<string, string> = {
        Positionable: 'positionable',
        Sizable: 'sizable',
        Rotatable: 'rotatable',
        Viewable: 'viewable',
        Interactable: 'interactable',
        Timeable: 'timeable',
    }

    for (const [functionName, bundle] of Object.entries(generated.mixins)) {
        const prefix = mixinExportName[functionName]
        if (bundle.propsTypeDef) {
            lines.push(`export const ${prefix}PropsTypeDef = \`${esc(bundle.propsTypeDef)}\``)
        }
        lines.push(`export const ${prefix}Api = \`${esc(bundle.api)}\``, '')
    }

    for (const [className, bundle] of Object.entries(generated.concreteClasses)) {
        const prefix = className.charAt(0).toLowerCase() + className.slice(1)
        lines.push(
            `export const ${prefix}PropsFields = \`${esc(bundle.propsFields.join('\n\n'))}\``,
            `export const ${prefix}Members = \`${esc(bundle.members.join('\n\n'))}\``,
            ''
        )
    }

    const outDir = apiPath('generated')
    mkdirSync(outDir, { recursive: true })
    const outFile = path.join(outDir, 'apiDeclarations.generated.ts')
    writeFileSync(outFile, lines.join('\n'), 'utf8')
    console.log(`Wrote ${path.relative(path.resolve(__dirname, '..'), outFile)}`)
}

main()
