import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { generateApiDeclarations } from './api-codegen/index'
import { renderGeneratedModule } from './api-codegen/render'
import { apiPath } from './api-codegen/sources'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function main() {
    const generated = generateApiDeclarations()
    const content = renderGeneratedModule(generated, [
        '// AUTO-GENERATED by `pnpm run generate-api` — do not edit directly.',
        '// Regenerate after changing any mixin or concrete class in src/assets/api/.',
    ])

    const outDir = apiPath('generated')
    mkdirSync(outDir, { recursive: true })
    const outFile = path.join(outDir, 'apiDeclarations.generated.ts')
    writeFileSync(outFile, content, 'utf8')
    console.log(`Wrote ${path.relative(path.resolve(__dirname, '..'), outFile)}`)
}

main()
