import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import ts from 'typescript'
import { generateApiDeclarations } from './api-codegen/index'
import { createProgram } from './api-codegen/extract'
import { findTypeAlias } from './api-codegen/ast'
import { CONCRETE_CLASSES, apiPath } from './api-codegen/sources'

const MIXIN_TYPE_NAMES: Record<string, string> = {
    Positionable: 'PositionableProps',
    Sizable: 'SizableProps',
    Rotatable: 'RotatableProps',
    Viewable: 'ViewableProps',
    Interactable: 'InteractableProps',
}

/** The `Base &` prefix of a concrete class's own `*Props` type (e.g. `RotatableProps & ViewableProps &` for Line). */
function findPropsBasePrefix(program: ts.Program, file: string, typeName: string): string {
    const sourceFile = program.getSourceFile(file)
    if (!sourceFile) return ''
    const typeAlias = findTypeAlias(sourceFile, typeName)
    if (!typeAlias || !ts.isIntersectionTypeNode(typeAlias.type)) return ''

    const baseMembers = typeAlias.type.types.slice(0, -1)
    if (baseMembers.length === 0) return ''
    return baseMembers.map((t) => t.getText(sourceFile)).join(' & ') + ' & '
}

function main() {
    const version = process.argv[2]
    if (!version) {
        console.error('Usage: pnpm run snapshot-api -- <version>  (e.g. pnpm run snapshot-api -- 1.0.0)')
        process.exit(1)
    }

    const outDir = apiPath('versions', version)
    if (existsSync(outDir)) {
        console.error(`versions/${version}/ already exists — snapshots are permanent, pick a new version label.`)
        process.exit(1)
    }

    const generated = generateApiDeclarations()
    const { program } = createProgram()

    const lines: string[] = [
        `// Sunsprite API declarations, version ${version}.`,
        '// Generated by `pnpm run snapshot-api` — a permanent, historical snapshot. Do not edit.',
        '',
        // Supporting types referenced below but not themselves snapshotted — imported
        // from real source so this file resolves standalone rather than relying on
        // this project's own skipLibCheck to silently paper over dangling references.
        'import type { Point, PointArg } from "../../Point"',
        'import type { Returnable, MouseInputAction, PointerAction, ScrollAction } from "../../types"',
        'import type { Cursor } from "../../mixins/Interactable"',
        '',
    ]

    for (const [functionName, typeName] of Object.entries(MIXIN_TYPE_NAMES)) {
        const bundle = generated.mixins[functionName]
        if (!bundle) continue
        lines.push(`export type ${typeName} = {\n${bundle.propsFields.join('\n\n')}\n}`, '')
    }

    lines.push(
        'export type GameObjectProps = PositionableProps & SizableProps & RotatableProps & InteractableProps & ViewableProps',
        ''
    )

    for (const concrete of CONCRETE_CLASSES) {
        const bundle = generated.concreteClasses[concrete.className]
        if (!bundle) continue
        const basePrefix = findPropsBasePrefix(program, concrete.file, concrete.typeName)

        lines.push(
            `export type ${concrete.typeName} = ${basePrefix}{\n${bundle.propsFields.join('\n\n')}\n}`,
            '',
            `export declare class ${concrete.className} {`,
            `    constructor(options?: ${concrete.typeName})`,
            '',
            bundle.members.join('\n\n'),
            '}',
            ''
        )
    }

    mkdirSync(outDir, { recursive: true })
    const outFile = path.join(outDir, 'api.d.ts')
    writeFileSync(outFile, lines.join('\n'), 'utf8')
    console.log(`Wrote src/assets/api/versions/${version}/api.d.ts`)
}

main()
