import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import ts from 'typescript'
import { generateApiDeclarations } from './api-codegen/index'
import { renderGeneratedModule } from './api-codegen/render'
import { createProgram } from './api-codegen/extract'
import { findTypeAlias } from './api-codegen/ast'
import { CONCRETE_CLASSES, apiPath, docsCopySet, runtimeCopySet } from './api-codegen/sources'
import { copyAndRewriteRuntime, verifyStandalone, normalizeSlashes } from './api-codegen/runtimeCopy'
import { copyAndRewriteVueFiles, verifyVueStandalone } from './api-codegen/vueCopy'
import { DEV_VERSION } from '../src/assets/api/versions/constants'

const MIXIN_TYPE_NAMES: Record<string, string> = {
    Positionable: 'PositionableProps',
    Sizable: 'SizableProps',
    Rotatable: 'RotatableProps',
    Viewable: 'ViewableProps',
    Interactable: 'InteractableProps',
}

/** The `Base &` prefix of a concrete class's own `*Props` type (e.g. `RotatableProps & ViewableProps &` for Line). */
function findPropsBasePrefix(program: ts.Program, file: string, typeName: string): string {
    const sourceFile = program.getSourceFile(file)
    if (!sourceFile) return ''
    const typeAlias = findTypeAlias(sourceFile, typeName)
    if (!typeAlias || !ts.isIntersectionTypeNode(typeAlias.type)) return ''

    const baseMembers = typeAlias.type.types.slice(0, -1)
    if (baseMembers.length === 0) return ''
    return baseMembers.map((t) => t.getText(sourceFile)).join(' & ') + ' & '
}

function main() {
    const version = process.argv[2]
    if (!version) {
        console.error('Usage: pnpm run snapshot-api -- <version>  (e.g. pnpm run snapshot-api -- 1.0.0)')
        process.exit(1)
    }

    // 'dev' isn't a folder — it's the reserved id for the live source (see
    // src/assets/api/versions/constants.ts). A versions/dev/ directory would be
    // picked up by index.ts's and runtime.ts's globs and shadow that entry with
    // a frozen copy of the very thing it exists to bypass, so the editor would
    // silently start offering a stale "dev".
    if (version === DEV_VERSION) {
        console.error(`"${DEV_VERSION}" is reserved for the live, unsnapshotted API — pick a numeric version label.`)
        process.exit(1)
    }

    const outDir = apiPath('versions', version)
    if (existsSync(outDir)) {
        console.error(`versions/${version}/ already exists — snapshots are permanent, pick a new version label.`)
        process.exit(1)
    }

    const generated = generateApiDeclarations()
    const { program } = createProgram()

    const lines: string[] = [
        `// Sunsprite API declarations, version ${version}.`,
        '// Generated by `pnpm run snapshot-api` — a permanent, historical snapshot. Do not edit.',
        '',
        // Supporting types referenced below but not themselves snapshotted — imported
        // from real source so this file resolves standalone rather than relying on
        // this project's own skipLibCheck to silently paper over dangling references.
        'import type { Point, PointArg } from "../../Point"',
        'import type { Returnable, MouseInputAction, PointerAction, ScrollAction } from "../../types"',
        'import type { Cursor } from "../../mixins/Interactable"',
        '',
    ]

    for (const [functionName, typeName] of Object.entries(MIXIN_TYPE_NAMES)) {
        const bundle = generated.mixins[functionName]
        if (!bundle) continue
        lines.push(`export type ${typeName} = {\n${bundle.propsFields.join('\n\n')}\n}`, '')
    }

    lines.push(
        'export type GameObjectProps = PositionableProps & SizableProps & RotatableProps & InteractableProps & ViewableProps',
        ''
    )

    for (const concrete of CONCRETE_CLASSES) {
        const bundle = generated.concreteClasses[concrete.className]
        if (!bundle) continue

        if (concrete.typeName) {
            // Options-constructed classes (Sprite, Rectangle, ...): real `*Props` type plus `constructor(options?: XProps)`.
            const basePrefix = findPropsBasePrefix(program, concrete.file, concrete.typeName)
            lines.push(
                `export type ${concrete.typeName} = ${basePrefix}{\n${bundle.propsFields.join('\n\n')}\n}`,
                '',
                `export declare class ${concrete.className} {`,
                `    constructor(options?: ${concrete.typeName})`,
                '',
                bundle.members.join('\n\n'),
                '}',
                ''
            )
        } else if (concrete.constructorParams !== undefined) {
            // Real classes user code constructs directly (Vector2, Timer) — no `*Props` type, a hand-known positional constructor.
            lines.push(
                `export declare class ${concrete.className} {`,
                `    constructor(${concrete.constructorParams})`,
                '',
                bundle.members.join('\n\n'),
                '}',
                ''
            )
        } else {
            // Singleton instances the real api object exposes directly (Camera, Screen, Clock, Mouse) — never constructed by user code.
            lines.push(
                `export declare const ${concrete.className}: {`,
                bundle.members.join('\n\n'),
                '}',
                ''
            )
        }
    }

    mkdirSync(outDir, { recursive: true })

    const outFile = path.join(outDir, 'api.d.ts')
    writeFileSync(outFile, lines.join('\n'), 'utf8')
    console.log(`Wrote src/assets/api/versions/${version}/api.d.ts`)

    // A second artifact, alongside the human-readable one above: the same
    // bare, ambient-ready string constants generate-api.ts writes for
    // "current", frozen for this version — what the editor actually loads
    // when hot-swapping to a historical version (see src/assets/api/versions/index.ts
    // and apiLib.ts's buildApiLib). api.d.ts's real `export type`/`import type`
    // syntax is for reading, not for splicing into Monaco's `declare global` lib.
    const generatedFile = path.join(outDir, 'generated.ts')
    const generatedContent = renderGeneratedModule(generated, [
        `// Sunsprite API declarations, version ${version} — Monaco-ready form.`,
        '// Generated by `pnpm run snapshot-api`, alongside api.d.ts. Do not edit.',
    ])
    writeFileSync(generatedFile, generatedContent, 'utf8')
    console.log(`Wrote src/assets/api/versions/${version}/generated.ts`)

    // The real, runnable source behind the declarations above — not just what
    // Monaco thinks is available, what actually executes. Verified standalone
    // before anything is left looking like a complete, permanent snapshot.
    const srcOutDir = path.join(outDir, 'src')
    const copiedFiles = copyAndRewriteRuntime(runtimeCopySet(), srcOutDir)

    // core.ts's exported VERSION is a human-maintained label for the live
    // source (see its own "Sunsprite v${VERSION} session" banner) — freeze
    // this snapshot's copy to the version being cut here rather than
    // whatever the live source happened to say when this ran, so a snapshot
    // is never left carrying a stale or since-bumped label.
    const copiedCoreFile = copiedFiles.find((f) => normalizeSlashes(f).endsWith('src/assets/api/core.ts'))
    if (!copiedCoreFile) throw new Error('snapshot-api: copied core.ts not found among runtime copy set')
    const coreContent = readFileSync(copiedCoreFile, 'utf8')
    const versionConstantPattern = /export const VERSION = ['"][^'"]*['"]/
    if (!versionConstantPattern.test(coreContent)) {
        throw new Error(`snapshot-api: could not find "export const VERSION = ..." in ${copiedCoreFile}`)
    }
    writeFileSync(copiedCoreFile, coreContent.replace(versionConstantPattern, `export const VERSION = '${version}'`), 'utf8')

    verifyStandalone(copiedFiles)
    console.log(`Wrote ${copiedFiles.length} runtime source files under src/assets/api/versions/${version}/src/`)

    // Doc pages under content/api/ — the only part of the docs frozen per
    // version (see docs/plans/api-versioning.md). Some (colors.vue, the
    // random/*.vue pages) import real API modules for live examples, so they
    // get resolved against the *union* of the runtime copy set and the docs
    // copy set, not docsCopySet() alone — that's what makes e.g. a page's
    // `@/assets/api/Colors` import land on this version's own already-copied
    // Colors.ts instead of the live original.
    const docsFiles = docsCopySet()
    const copiedDocsFiles = copyAndRewriteVueFiles(docsFiles, [...runtimeCopySet(), ...docsFiles], srcOutDir)
    verifyVueStandalone(copiedDocsFiles)
    console.log(`Wrote ${copiedDocsFiles.length} doc pages under src/assets/api/versions/${version}/src/assets/docs/content/api/`)
}

main()
